name: Daily Challenge Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run generator
        run: |
          python DailyChallengeGen.py
      - name: Commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add challenges/*.json
          git commit -m "Update daily challenge"
          git push
